# Generated by Django 4.2.2 on 2023-06-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wl_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='wl_user',
            new_name='user',
        ),
    ]
